name: flutter_resep_makanan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  http: ^0.13.6
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/img/logoLauncher.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/img/logoLauncher.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/img/logoLauncher.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/img/logoLauncher.png'
