// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChPNUY6QSKJA2FCU3Q2OYnh7Q0mv_DZcQ',
    appId: '1:416812175120:web:3f2e030eb3d66266235f95',
    messagingSenderId: '416812175120',
    projectId: 'flutter-resep-makanan',
    authDomain: 'flutter-resep-makanan.firebaseapp.com',
    storageBucket: 'flutter-resep-makanan.appspot.com',
    measurementId: 'G-MF0YL2PV1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72wtgFdrm1hEaC-RNiQxqi4OWWAGnNaY',
    appId: '1:416812175120:android:78e2949a35928663235f95',
    messagingSenderId: '416812175120',
    projectId: 'flutter-resep-makanan',
    storageBucket: 'flutter-resep-makanan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB14PFJC7cDCU1ucta_MT1wfDZ47f9MTfI',
    appId: '1:416812175120:ios:b5da6e12248929ca235f95',
    messagingSenderId: '416812175120',
    projectId: 'flutter-resep-makanan',
    storageBucket: 'flutter-resep-makanan.appspot.com',
    iosBundleId: 'com.example.flutterResepMakanan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB14PFJC7cDCU1ucta_MT1wfDZ47f9MTfI',
    appId: '1:416812175120:ios:cc3c957aee4e7153235f95',
    messagingSenderId: '416812175120',
    projectId: 'flutter-resep-makanan',
    storageBucket: 'flutter-resep-makanan.appspot.com',
    iosBundleId: 'com.example.flutterResepMakanan.RunnerTests',
  );
}
